/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.SalesGroup;

import DAO.Ban_DAO;
import DAO.ChiTietHoaDon_DAO;
import DAO.HoaDon_DAO;
import POJO.Ban;
import POJO.HoaDon;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class JF_ChuyenBan extends javax.swing.JFrame {

    HoaDon hoaDon;
    Ban ban;

    /**
     * Creates new form JF_ChuyenBan
     */
    private void load_cboBanTrong() {
        Vector<Ban> comboData = new Vector<>();
        for (Ban ban : Ban_DAO.layDanhSach(0)) {
            comboData.add(ban);
        }
        if (comboData.isEmpty()) {
            cbo_BanTrong.setEnabled(false);
            lb_HetBan.setVisible(true);
        } else {
            cbo_BanTrong.setModel(new DefaultComboBoxModel<>(comboData));
            cbo_BanTrong.setSelectedIndex(0);
        }
    }

    public JF_ChuyenBan(Ban ban) {
        initComponents();
        this.ban = ban;
        lb_HetBan.setVisible(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);

        load_cboBanTrong();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbo_BanTrong = new javax.swing.JComboBox<>();
        lb_HetBan = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_XacNhan = new Assets.Custom_Item.ButtonRound();
        btn_Thoat = new Assets.Custom_Item.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(223, 164, 88));

        jPanel1.setBackground(new java.awt.Color(223, 164, 88));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách bàn trống");

        cbo_BanTrong.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cbo_BanTrong.setMinimumSize(new java.awt.Dimension(266, 38));

        lb_HetBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_HetBan.setForeground(new java.awt.Color(255, 0, 0));
        lb_HetBan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_HetBan.setText("Không còn bàn trống");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbo_BanTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(lb_HetBan, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbo_BanTrong, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_HetBan)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(223, 164, 88));

        btn_XacNhan.setText("Xác nhận");
        btn_XacNhan.setBorderColor(new java.awt.Color(255, 255, 255));
        btn_XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_XacNhan.setRadius(20);
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });

        btn_Thoat.setText("Thoát");
        btn_Thoat.setBorderColor(new java.awt.Color(255, 255, 255));
        btn_Thoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Thoat.setRadius(20);
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Thoat, btn_XacNhan});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Thoat, btn_XacNhan});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        if (cbo_BanTrong.isEnabled()) {
            // Lấy bàn trống đã chọn từ combo box
            Ban ban = (Ban) cbo_BanTrong.getSelectedItem();
            int n = JOptionPane.showConfirmDialog(this, "Chuyển dữ liệu từ bàn " + this.ban.getSoBan() + " sang bàn " + ban.getSoBan() + "?", "Xác nhận chuyển bàn", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (n == JOptionPane.YES_OPTION) {
                // Chuyển bàn

                // Cập nhật số bàn cho hóa đơn
                hoaDon = HoaDon_DAO.layHoaDonCuaBanDangSuDung(this.ban.getSoBan());
                hoaDon.setBan(ban.getSoBan());
                HoaDon_DAO.sua(hoaDon);                

                // Thay đổi trạng thái của 2 bàn
                Ban_DAO.thayDoiTrangThai(ban);
                Ban_DAO.thayDoiTrangThai(this.ban);
                JOptionPane.showMessageDialog(null, "Chuyển bàn thành công!");
                Fr_BanHang.load_panelBan(Fr_BanHang.trangThaiBan);
            } else {
                return;
            }
        }
        dispose();

    }//GEN-LAST:event_btn_XacNhanActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        dispose();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Assets.Custom_Item.ButtonRound btn_Thoat;
    private Assets.Custom_Item.ButtonRound btn_XacNhan;
    private javax.swing.JComboBox<Ban> cbo_BanTrong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_HetBan;
    // End of variables declaration//GEN-END:variables
}
