/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.SalesGroup;

import DAO.Ban_DAO;
import DAO.ChiTietHoaDon_DAO;
import DAO.HoaDon_DAO;
import POJO.Ban;
import POJO.ChiTietHoaDon;
import POJO.HoaDon;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class JF_GopBan extends javax.swing.JFrame {

    private HoaDon hoaDon;
    private Ban ban;

    /**
     * Creates new form JF_GopBan
     */
    private void load_cboBanDangSuDung() {
        Vector<Ban> comboData = new Vector<>();
        for (Ban ban : Ban_DAO.layDanhSach(1)) {
            if (ban.getSoBan() == this.ban.getSoBan()) {
                continue;
            }
            comboData.add(ban);
        }
        if (comboData.isEmpty()) {
            cbo_BanDangSuDung.setEnabled(false);
            lb_ThongBao.setVisible(true);
        } else {
            cbo_BanDangSuDung.setModel(new DefaultComboBoxModel<>(comboData));
            cbo_BanDangSuDung.setSelectedIndex(0);
            btn_Ban2.setText(((Ban) cbo_BanDangSuDung.getSelectedItem()).getSoBan() + "");
        }
    }

    public JF_GopBan(Ban ban) {
        initComponents();

        this.ban = ban;
        hoaDon = HoaDon_DAO.layHoaDonCuaBanDangSuDung(ban.getSoBan());
        lb_ThongBao.setVisible(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        btn_Ban1.setText(String.valueOf(ban));
        load_cboBanDangSuDung();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbo_BanDangSuDung = new javax.swing.JComboBox<>();
        lb_ThongBao = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_Thoat = new Assets.Custom_Item.ButtonRound();
        jPanel3 = new javax.swing.JPanel();
        btn_Ban1 = new Assets.Custom_Item.ButtonRound();
        btn_Ban2 = new Assets.Custom_Item.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(223, 164, 88));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Danh sách đang sử dụng");

        cbo_BanDangSuDung.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cbo_BanDangSuDung.setMinimumSize(new java.awt.Dimension(266, 38));
        cbo_BanDangSuDung.setPreferredSize(new java.awt.Dimension(266, 38));
        cbo_BanDangSuDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_BanDangSuDungActionPerformed(evt);
            }
        });

        lb_ThongBao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lb_ThongBao.setForeground(new java.awt.Color(255, 0, 0));
        lb_ThongBao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_ThongBao.setText("Không có bàn đang sử dụng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lb_ThongBao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_BanDangSuDung, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbo_BanDangSuDung, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_ThongBao)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(223, 164, 88));

        btn_Thoat.setText("Thoát");
        btn_Thoat.setBorderColor(new java.awt.Color(255, 255, 255));
        btn_Thoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Thoat.setRadius(20);
        btn_Thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThoatActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(223, 164, 88));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(138, 91, 43)), "Chọn bàn gộp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(223, 164, 88));

        btn_Ban1.setText("1");
        btn_Ban1.setBorderColor(new java.awt.Color(255, 255, 255));
        btn_Ban1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Ban1.setRadius(20);
        btn_Ban1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ban1ActionPerformed(evt);
            }
        });

        btn_Ban2.setText("2");
        btn_Ban2.setBorderColor(new java.awt.Color(255, 255, 255));
        btn_Ban2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_Ban2.setRadius(20);
        btn_Ban2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Ban2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btn_Ban1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(btn_Ban2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Ban1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Ban2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(btn_Thoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gopBan(int soBan) {
        if (cbo_BanDangSuDung.isEnabled()) {
            // Lấy bàn đã chọn từ combo box
            Ban ban = (Ban) cbo_BanDangSuDung.getSelectedItem();
            int n = JOptionPane.showConfirmDialog(this,
                    "Gộp thông tin của bàn " + this.ban.getSoBan() + " và bàn " + ban.getSoBan() + "?",
                    "Xác nhận gộp bàn", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (n == JOptionPane.YES_OPTION) {
                // Gộp bàn
                // Lấy hóa đơn của bàn 2
                HoaDon hoaDon2 = HoaDon_DAO.layHoaDonCuaBanDangSuDung(ban.getSoBan());
                // Tìm hóa đơn có trước và sau
                HoaDon hoaDonTruoc = new HoaDon(hoaDon2);
                HoaDon hoaDonSau = new HoaDon(hoaDon);
                if (hoaDon2.getMaHoaDon() > hoaDon.getMaHoaDon()) {
                    hoaDonTruoc = new HoaDon(hoaDon);
                    hoaDonSau = new HoaDon(hoaDon2);
                }
                // Cập nhật chi tiết hóa đơn của hóa đơn sau vào hóa đơn trước
                ArrayList<ChiTietHoaDon> list = new ArrayList<>();
                ArrayList<ChiTietHoaDon> list2 = ChiTietHoaDon_DAO.layDanhSach(hoaDonTruoc.getMaHoaDon());

                for (ChiTietHoaDon cthd : ChiTietHoaDon_DAO.layDanhSach(hoaDonSau.getMaHoaDon())) {
                    cthd.setMaHoaDon(hoaDonTruoc.getMaHoaDon());
                    for (ChiTietHoaDon e : list2) {
                        if (e.getMaSanPham() == cthd.getMaSanPham()) {
                            cthd.setSoLuong(cthd.getSoLuong() + e.getSoLuong());
                            list2.remove(e);
                            break;
                        }
                    }
                    list.add(cthd);
                }
                list2.forEach(e -> {
                    list.add(e);
                });
                // Xoá cthd cũ trong db
                ChiTietHoaDon_DAO.xoa(hoaDonTruoc.getMaHoaDon());

                // Tạo cthd mới
                for (ChiTietHoaDon cthd : list) {
                    try {
                        cthd.setTongTien(cthd.getGiaSanPham()*cthd.getSoLuong());
                        ChiTietHoaDon_DAO.them(cthd);
                    } catch (SQLException ex) {
                        Logger.getLogger(JF_GopBan.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                // Xoá hóa đơn sau
                ChiTietHoaDon_DAO.xoaTheoHoaDon(hoaDonSau.getMaHoaDon());
                HoaDon_DAO.xoa(hoaDonSau.getMaHoaDon());

                // Cập nhật số bàn cho hóa đơn
                hoaDonTruoc.setBan(soBan);
                HoaDon_DAO.sua(hoaDonTruoc);

                // Bỏ trạng thái đang sử dụng của bàn còn lại
                Ban_DAO.thayDoiTrangThai(soBan != ban.getSoBan() ? ban : this.ban);

                JOptionPane.showMessageDialog(null, "Gộp bàn thành công!");

                Fr_BanHang.load_panelBan(Fr_BanHang.trangThaiBan);
                dispose();
            }
        }
    }


    private void btn_Ban1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ban1ActionPerformed
        gopBan(Integer.parseInt(btn_Ban1.getText()));
    }//GEN-LAST:event_btn_Ban1ActionPerformed

    private void btn_ThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThoatActionPerformed
        dispose();
    }//GEN-LAST:event_btn_ThoatActionPerformed

    private void btn_Ban2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Ban2ActionPerformed
        // TODO add your handling code here:
        gopBan(Integer.parseInt(btn_Ban2.getText()));
    }//GEN-LAST:event_btn_Ban2ActionPerformed

    private void cbo_BanDangSuDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_BanDangSuDungActionPerformed
        // TODO add your handling code here:
        btn_Ban2.setText(((Ban) cbo_BanDangSuDung.getSelectedItem()).getSoBan() + "");
    }//GEN-LAST:event_cbo_BanDangSuDungActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Assets.Custom_Item.ButtonRound btn_Ban1;
    private Assets.Custom_Item.ButtonRound btn_Ban2;
    private Assets.Custom_Item.ButtonRound btn_Thoat;
    private javax.swing.JComboBox<Ban> cbo_BanDangSuDung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lb_ThongBao;
    // End of variables declaration//GEN-END:variables
}
