/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.SalesGroup;

import DAO.HoaDon_DAO;
import POJO.HoaDon;
import POJO.NhanVien;
import java.awt.Font;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Stack;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class JF_LichSu extends javax.swing.JFrame {

    SimpleDateFormat sdf = new SimpleDateFormat("hh:mm:ss dd/MM/yyyy");


    

    /**
     * Creates new form JF_LichSu
     */
    private void load_HoaDon() {
        try {
            DefaultTableModel dtm = new DefaultTableModel();
            String[] tieuDe = new String[]{"Số hóa đơn", "Thành tiền", "Thời gian lập", "Thời gian thanh toán", "Số khách", "Bàn", "Nhân viên thực hiện"};

            dtm.setColumnIdentifiers(tieuDe);
            dtm.setRowCount(0);

            //Load dữ liệu
            for (HoaDon hoaDon : HoaDon_DAO.layDanhSach()) {
                try {
                    Vector<Object> v = new Stack<>();
                    v.add(hoaDon.getMaHoaDon());
                    v.add(hoaDon.getThanhTien());
                    v.add(sdf.format(hoaDon.getThoiGianLap()));
                    if (hoaDon.getThoiGianThanhToan() == null) {
                        v.add("");
                    } else {
                        v.add(sdf.format(hoaDon.getThoiGianThanhToan()));
                    }
                    v.add(hoaDon.getSoKhach());
                    v.add(hoaDon.getBan());
                    String tenNhanVien = (new NhanVien()).getTenNhanVien(hoaDon.getMaNhanVien());
                    v.add(tenNhanVien);
                    dtm.addRow(v);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Lỗi: " + ex.getMessage());
                }
            }
            table.setModel(dtm);

            table.setFont(new Font("Tahoma", Font.PLAIN, 16));
            table.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 16));      
            table.setRowHeight(30);

            int i =0;
            int width = table.getWidth();
            table.getColumnModel().getColumn(i++).setPreferredWidth((int) (width*0.1));
            table.getColumnModel().getColumn(i++).setPreferredWidth((int) (width*0.1));
            table.getColumnModel().getColumn(i++).setPreferredWidth((int) (width*0.2));
            table.getColumnModel().getColumn(i++).setPreferredWidth((int) (width*0.2));
            table.getColumnModel().getColumn(i++).setPreferredWidth((int) (width*0.1));
            table.getColumnModel().getColumn(i++).setPreferredWidth((int) (width*0.1));
            table.getColumnModel().getColumn(i++).setPreferredWidth((int) (width*0.2));
            
        } catch (ParseException ex) {
            Logger.getLogger(JF_LichSu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void load_ChiTietHoaDon() {

    }

    private void load_Form() {
        setLocationRelativeTo(null);
        load_HoaDon();
    }

    public JF_LichSu() {
        initComponents(); 
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        load_Form();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        buttonRound1 = new Assets.Custom_Item.ButtonRound();
        buttonRound2 = new Assets.Custom_Item.ButtonRound();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(222, 184, 135));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lịch sử");

        buttonRound1.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound1.setText("In hóa đơn");
        buttonRound1.setBorderColor(new java.awt.Color(0, 0, 0));
        buttonRound1.setColorOver(new java.awt.Color(163, 137, 122));
        buttonRound1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonRound1.setRadius(30);

        buttonRound2.setForeground(new java.awt.Color(255, 255, 255));
        buttonRound2.setText("Xem chi tiết");
        buttonRound2.setBorderColor(new java.awt.Color(0, 0, 0));
        buttonRound2.setColorOver(new java.awt.Color(163, 137, 122));
        buttonRound2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        buttonRound2.setRadius(30);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {buttonRound1, buttonRound2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {buttonRound1, buttonRound2});

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_LichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_LichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_LichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_LichSu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_LichSu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Assets.Custom_Item.ButtonRound buttonRound1;
    private Assets.Custom_Item.ButtonRound buttonRound2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
