/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.SalesGroup;

import BUS.Supporter;
import DAO.NguyenLieu_DAO;
import DAO.PhieuXuat_DAO;
import GUI.Fr_Login;
import POJO.NguyenLieu;
import POJO.PhieuXuat;

import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author huyng
 */
public class JF_PhieuXuatNguyenLieu extends javax.swing.JFrame {

    static SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

    /**
     * Creates new form JF_PhieuThemSP
     */
    private void load_Form() {
        setLocationRelativeTo(null);
        dongForm();
        load_cboNguyenLieu();
        txt_TenNV.setText(Fr_Login.nhanVien.getTenNhanVien());
        Supporter.ganPhim(KeyEvent.VK_ESCAPE, "Huy", btn_Huy, () -> btn_HuyActionPerformed(null));
        Supporter.ganPhim(KeyEvent.VK_ENTER, "XacNhan", btn_XacNhan, () -> btn_XacNhanActionPerformed(null));
    }

    private void dongForm() {
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                setVisible(false);
            }
        });
    }

    private void load_cboNguyenLieu() {
        Vector<NguyenLieu> comboData = new Vector<>();
        comboData.add(new NguyenLieu(0, "Nguyên liệu"));
        for (NguyenLieu nguyenLieu : NguyenLieu_DAO.layDanhSach()) {
            comboData.add(nguyenLieu);
        }
        cbo_NguyenLieu.setModel(new DefaultComboBoxModel<>(comboData));
    }

    public JF_PhieuXuatNguyenLieu() {
        initComponents();
        load_Form();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_ThemSanPham = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        cbo_NguyenLieu = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        nr_SoLuong = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        lb_SoLuongTon = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        txt_TenNV = new javax.swing.JLabel();
        txt_NgayXuat = new Assets.Custom_Item.TextFieldR_Login();
        jPanel5 = new javax.swing.JPanel();
        btn_XacNhan = new Assets.Custom_Item.ButtonRound();
        btn_Huy = new Assets.Custom_Item.ButtonRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(222, 184, 135));

        jPanel1.setBackground(new java.awt.Color(222, 184, 135));

        pnl_ThemSanPham.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));
        pnl_ThemSanPham.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnl_ThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnl_ThemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(222, 184, 135));

        jPanel3.setBackground(new java.awt.Color(222, 184, 135));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel16.setText("Tên nguyên liệu");

        cbo_NguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_NguyenLieuActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setText("Số lượng");

        nr_SoLuong.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nr_SoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nr_SoLuongStateChanged(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(222, 184, 135));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Số lượng tồn", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        jPanel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lb_SoLuongTon.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lb_SoLuongTon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_SoLuongTon, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_SoLuongTon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbo_NguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nr_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel15, jLabel16});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(cbo_NguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(nr_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(138, 91, 43));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setText("Phiếu xuất");
        jPanel12.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, -1, 26));

        txt_TenNV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        txt_TenNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_TenNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-user-30.png"))); // NOI18N
        txt_TenNV.setText("    Tên nhân viên ");
        jPanel12.add(txt_TenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txt_NgayXuat.setEditable(false);
        txt_NgayXuat.setText(sdf.format(new Date()));
        txt_NgayXuat.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txt_NgayXuat.setLabelText("Ngày xuất");
        jPanel12.add(txt_NgayXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 150, -1));

        jPanel5.setBackground(new java.awt.Color(222, 184, 135));

        btn_XacNhan.setText("Xác Nhận");
        btn_XacNhan.setBorderColor(new java.awt.Color(255, 255, 255));
        btn_XacNhan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_XacNhan.setRadius(20);
        btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XacNhanActionPerformed(evt);
            }
        });

        btn_Huy.setText("Hủy");
        btn_Huy.setBorderColor(new java.awt.Color(255, 255, 255));
        btn_Huy.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_Huy.setRadius(20);
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_XacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 570, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 307, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XacNhanActionPerformed
        try {
            Date ngayXuat = null;
            ngayXuat = sdf.parse(txt_NgayXuat.getText());

            int maNguyenLieu = ((NguyenLieu) cbo_NguyenLieu.getSelectedItem()).getMaNguyenLieu();
            int soLuong = (int) nr_SoLuong.getValue();

            PhieuXuat_DAO.them(new PhieuXuat(maNguyenLieu, soLuong, ngayXuat, Fr_Login.nhanVien.getMaNhanVien()));
            JOptionPane.showMessageDialog(null, "Xuất nguyên liệu thành công");
            dispose();
        } catch (SQLException | ParseException ex) {
            Logger.getLogger(JF_PhieuXuatNguyenLieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_XacNhanActionPerformed

    private void cbo_NguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_NguyenLieuActionPerformed
        // TODO add your handling code here:
        NguyenLieu nguyenLieu = (NguyenLieu) cbo_NguyenLieu.getSelectedItem();
        lb_SoLuongTon.setText(String.valueOf(nguyenLieu.getSoLuongTon()));

        if ("0".equals(lb_SoLuongTon.getText())) {
            nr_SoLuong.setEnabled(false);
            nr_SoLuong.setValue(0);
        } else {
            nr_SoLuong.setEnabled(true);
            nr_SoLuong.setValue(1);
        }


    }//GEN-LAST:event_cbo_NguyenLieuActionPerformed

    private void nr_SoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nr_SoLuongStateChanged
        int soLuong = (int) nr_SoLuong.getValue();
        int max = Integer.parseInt(lb_SoLuongTon.getText());
        if (soLuong < 1 && !"0".equals(lb_SoLuongTon.getText())) {
            nr_SoLuong.setValue(1);
        }
        if (soLuong > max) {
            nr_SoLuong.setValue(max);
        }
    }//GEN-LAST:event_nr_SoLuongStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Assets.Custom_Item.ButtonRound btn_Huy;
    private Assets.Custom_Item.ButtonRound btn_XacNhan;
    private javax.swing.JComboBox<NguyenLieu> cbo_NguyenLieu;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lb_SoLuongTon;
    private javax.swing.JSpinner nr_SoLuong;
    private javax.swing.JPanel pnl_ThemSanPham;
    private Assets.Custom_Item.TextFieldR_Login txt_NgayXuat;
    private javax.swing.JLabel txt_TenNV;
    // End of variables declaration//GEN-END:variables
}
