/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI.ManagerGroup;

/**
 *
 * @author Admin
 */
public class JP_NCC extends javax.swing.JPanel {

    /**
     * Creates new form Panel_NCC
     */
    public JP_NCC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_NguyenLieu = new javax.swing.JPanel();
        menu_Item4 = new Assets.Custom_Item.Menu_Item();
        Panel_ToolbarSP2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txt_TenNhanVien2 = new javax.swing.JLabel();
        panelRound5 = new Assets.Custom_Item.PanelRound();
        jLabel32 = new javax.swing.JLabel();
        txt_Email = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        lb_Diachi = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        cbo_MaNCC = new javax.swing.JComboBox<>();
        btn_ThemNguyenLieu = new Assets.Custom_Item.ButtonRound();
        jLabel41 = new javax.swing.JLabel();
        txt_TenNCC = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_NCC = new javax.swing.JTable();

        Panel_NguyenLieu.setBackground(new java.awt.Color(138, 91, 43));
        Panel_NguyenLieu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Panel_NguyenLieu.add(menu_Item4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel_ToolbarSP2.setBackground(new java.awt.Color(222, 184, 135));
        Panel_ToolbarSP2.setPreferredSize(new java.awt.Dimension(1250, 60));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-user-30.png"))); // NOI18N

        txt_TenNhanVien2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txt_TenNhanVien2.setText("Tên nhân viên");

        javax.swing.GroupLayout Panel_ToolbarSP2Layout = new javax.swing.GroupLayout(Panel_ToolbarSP2);
        Panel_ToolbarSP2.setLayout(Panel_ToolbarSP2Layout);
        Panel_ToolbarSP2Layout.setHorizontalGroup(
            Panel_ToolbarSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_ToolbarSP2Layout.createSequentialGroup()
                .addContainerGap(994, Short.MAX_VALUE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_TenNhanVien2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        Panel_ToolbarSP2Layout.setVerticalGroup(
            Panel_ToolbarSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_ToolbarSP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_ToolbarSP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_TenNhanVien2)
                    .addComponent(jLabel22))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Panel_NguyenLieu.add(Panel_ToolbarSP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 60));

        panelRound5.setBackground(new java.awt.Color(222, 184, 135));
        panelRound5.setRoundBottomLeft(70);
        panelRound5.setRoundBottomRight(70);
        panelRound5.setRoundTopLeft(70);
        panelRound5.setRoundTopRight(70);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-warning-30.png"))); // NOI18N
        jLabel32.setText("Thông tin chi tiết");
        panelRound5.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        txt_Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmailActionPerformed(evt);
            }
        });
        panelRound5.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 158, 35));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel33.setText("Mã nhà cung cấp");
        panelRound5.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 140, -1));

        lb_Diachi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lb_Diachi.setText("Địa chỉ");
        panelRound5.add(lb_Diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, -1, -1));

        txt_DiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DiaChiActionPerformed(evt);
            }
        });
        panelRound5.add(txt_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 160, 35));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel40.setText("Email");
        panelRound5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 103, -1));

        cbo_MaNCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        panelRound5.add(cbo_MaNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 160, 30));

        btn_ThemNguyenLieu.setText("+");
        btn_ThemNguyenLieu.setBorderColor(new java.awt.Color(222, 184, 135));
        btn_ThemNguyenLieu.setColor(new java.awt.Color(223, 164, 88));
        btn_ThemNguyenLieu.setColorClick(new java.awt.Color(138, 91, 43));
        btn_ThemNguyenLieu.setColorOver(new java.awt.Color(223, 164, 88));
        btn_ThemNguyenLieu.setFont(new java.awt.Font("Varela Round", 1, 36)); // NOI18N
        btn_ThemNguyenLieu.setRadius(50);
        btn_ThemNguyenLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemNguyenLieuActionPerformed(evt);
            }
        });
        panelRound5.add(btn_ThemNguyenLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 50, 50));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel41.setText("Tên nhà cung cấp");
        panelRound5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, -1));

        txt_TenNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenNCCActionPerformed(evt);
            }
        });
        panelRound5.add(txt_TenNCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 158, 35));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel42.setText("Số điện thoại");
        panelRound5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 103, -1));

        txt_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDTActionPerformed(evt);
            }
        });
        panelRound5.add(txt_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 158, 35));

        Panel_NguyenLieu.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 670, 440));

        tbl_NCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "action"
            }
        ));
        tbl_NCC.setRowHeight(40);
        tbl_NCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_NCCMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_NCC);

        Panel_NguyenLieu.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 520, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1460, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panel_NguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 1460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1179, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Panel_NguyenLieu, javax.swing.GroupLayout.PREFERRED_SIZE, 1179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EmailActionPerformed

    private void txt_DiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DiaChiActionPerformed

    private void btn_ThemNguyenLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemNguyenLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ThemNguyenLieuActionPerformed

    private void txt_TenNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenNCCActionPerformed

    private void tbl_NCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_NCCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_NCCMouseClicked

    private void txt_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_NguyenLieu;
    private javax.swing.JPanel Panel_ToolbarSP2;
    private Assets.Custom_Item.ButtonRound btn_ThemNguyenLieu;
    private javax.swing.JComboBox<String> cbo_MaNCC;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lb_Diachi;
    private Assets.Custom_Item.Menu_Item menu_Item4;
    private Assets.Custom_Item.PanelRound panelRound5;
    private javax.swing.JTable tbl_NCC;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNCC;
    private javax.swing.JLabel txt_TenNhanVien2;
    // End of variables declaration//GEN-END:variables
}
