/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Assets.Custom_Item;

import GUI.SalesGroup.JF_ChuyenBan;
import GUI.SalesGroup.JF_GopBan;
import GUI.SalesGroup.JF_TachBan;
import POJO.Ban;
import java.awt.Color;

/**
 *
 * @author huyng
 */
public class Menu_QLBan extends javax.swing.JPanel {

    Color oldColor = new Color(138, 91, 43);
    Ban ban;

    /**
     * Creates new form Menu_Item
     * @param ban
     */
    public Menu_QLBan(Ban ban) {
        initComponents();
        P_MenuItem.setVisible(false);
        this.ban = ban;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new Assets.Custom_Item.PanelRound();
        jLabel4 = new javax.swing.JLabel();
        P_MenuItem = new javax.swing.JPanel();
        Item_TachBan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Item_ChuyenBan = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Item_GopBan = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(235, 213, 186));
        setOpaque(false);

        Menu.setBackground(new java.awt.Color(223, 164, 88));
        Menu.setRoundBottomRight(50);
        Menu.setRoundTopLeft(50);
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-menu-30.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        P_MenuItem.setBackground(new java.awt.Color(222, 184, 135));
        P_MenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_MenuItemMouseClicked(evt);
            }
        });

        Item_TachBan.setBackground(new java.awt.Color(223, 164, 88));
        Item_TachBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_TachBanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Item_TachBanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Item_TachBanMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-query-outer-join-30.png"))); // NOI18N
        jLabel2.setText("Tách bàn");

        javax.swing.GroupLayout Item_TachBanLayout = new javax.swing.GroupLayout(Item_TachBan);
        Item_TachBan.setLayout(Item_TachBanLayout);
        Item_TachBanLayout.setHorizontalGroup(
            Item_TachBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_TachBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Item_TachBanLayout.setVerticalGroup(
            Item_TachBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_TachBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Item_ChuyenBan.setBackground(new java.awt.Color(223, 164, 88));
        Item_ChuyenBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_ChuyenBanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Item_ChuyenBanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Item_ChuyenBanMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-swap-30.png"))); // NOI18N
        jLabel5.setText("Chuyển bàn");

        javax.swing.GroupLayout Item_ChuyenBanLayout = new javax.swing.GroupLayout(Item_ChuyenBan);
        Item_ChuyenBan.setLayout(Item_ChuyenBanLayout);
        Item_ChuyenBanLayout.setHorizontalGroup(
            Item_ChuyenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_ChuyenBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Item_ChuyenBanLayout.setVerticalGroup(
            Item_ChuyenBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_ChuyenBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Item_GopBan.setBackground(new java.awt.Color(223, 164, 88));
        Item_GopBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_GopBanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Item_GopBanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Item_GopBanMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-query-inner-join-30.png"))); // NOI18N
        jLabel3.setText("Gộp bàn");

        javax.swing.GroupLayout Item_GopBanLayout = new javax.swing.GroupLayout(Item_GopBan);
        Item_GopBan.setLayout(Item_GopBanLayout);
        Item_GopBanLayout.setHorizontalGroup(
            Item_GopBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_GopBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Item_GopBanLayout.setVerticalGroup(
            Item_GopBanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_GopBanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout P_MenuItemLayout = new javax.swing.GroupLayout(P_MenuItem);
        P_MenuItem.setLayout(P_MenuItemLayout);
        P_MenuItemLayout.setHorizontalGroup(
            P_MenuItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Item_ChuyenBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Item_GopBan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Item_TachBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        P_MenuItemLayout.setVerticalGroup(
            P_MenuItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_MenuItemLayout.createSequentialGroup()
                .addComponent(Item_TachBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_ChuyenBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_GopBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(P_MenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(P_MenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Item_GopBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_GopBanMouseClicked
        // TODO add your handling code here:
        new JF_GopBan(ban).setVisible(true);

    }//GEN-LAST:event_Item_GopBanMouseClicked

    private void Item_TachBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TachBanMouseClicked
        new JF_TachBan(ban).setVisible(true);
    }//GEN-LAST:event_Item_TachBanMouseClicked

    private void Item_ChuyenBanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_ChuyenBanMouseClicked
        new JF_ChuyenBan(ban).setVisible(true);

    }//GEN-LAST:event_Item_ChuyenBanMouseClicked

    private void P_MenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_MenuItemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_P_MenuItemMouseClicked

    private void Item_TachBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TachBanMouseExited
        // TODO add your handling code here:
        Item_TachBan.setBackground(new Color(223, 164, 88));

    }//GEN-LAST:event_Item_TachBanMouseExited

    private void Item_GopBanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_GopBanMouseEntered
        // TODO add your handling code here:
        Item_GopBan.setBackground(new Color(222, 184, 135));
    }//GEN-LAST:event_Item_GopBanMouseEntered

    private void Item_TachBanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TachBanMouseEntered
        // TODO add your handling code here:
        Item_TachBan.setBackground(new Color(222, 184, 135));
    }//GEN-LAST:event_Item_TachBanMouseEntered

    private void Item_ChuyenBanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_ChuyenBanMouseEntered
        // TODO add your handling code here:
        Item_ChuyenBan.setBackground(new Color(222, 184, 135));
    }//GEN-LAST:event_Item_ChuyenBanMouseEntered

    private void Item_GopBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_GopBanMouseExited
        // TODO add your handling code here:
        Item_GopBan.setBackground(new Color(223, 164, 88));
    }//GEN-LAST:event_Item_GopBanMouseExited

    private void Item_ChuyenBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_ChuyenBanMouseExited
        // TODO add your handling code here:
        Item_ChuyenBan.setBackground(new Color(223, 164, 88));
    }//GEN-LAST:event_Item_ChuyenBanMouseExited

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        // TODO add your handling code here:
        if (!P_MenuItem.isVisible()) {
            P_MenuItem.setVisible(true);
        } else {
            P_MenuItem.setVisible(false);
        }
    }//GEN-LAST:event_MenuMouseClicked
    public static void main(String[] args) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Item_ChuyenBan;
    private javax.swing.JPanel Item_GopBan;
    private javax.swing.JPanel Item_TachBan;
    private Assets.Custom_Item.PanelRound Menu;
    private javax.swing.JPanel P_MenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
