/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Assets.Custom_Item;

import GUI.Fr_Login;
import GUI.ManagerGroup.fr_CuaHang;
import GUI.SalesGroup.Fr_BanHang;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author huyng
 */
public class Menu_Item extends javax.swing.JPanel {

    Color oldColor = new Color(138, 91, 43);

    /**
     * Creates new form Menu_Item
     */
    public Menu_Item() {
        initComponents();
        P_MenuItem.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        P_MenuItem = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        Item_TaiKhoan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Item_TrangBanHang = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        Item_LichSu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Item_DangXuat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(222, 184, 135));

        Menu.setBackground(new java.awt.Color(222, 184, 135));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-menu-40.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        P_MenuItem.setBackground(new java.awt.Color(222, 184, 135));
        P_MenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                P_MenuItemMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(222, 184, 135));

        Item_TaiKhoan.setBackground(new java.awt.Color(138, 91, 43));
        Item_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_TaiKhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Item_TaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Item_TaiKhoanMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-user-30.png"))); // NOI18N
        jLabel2.setText("Tài khoản");

        javax.swing.GroupLayout Item_TaiKhoanLayout = new javax.swing.GroupLayout(Item_TaiKhoan);
        Item_TaiKhoan.setLayout(Item_TaiKhoanLayout);
        Item_TaiKhoanLayout.setHorizontalGroup(
            Item_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_TaiKhoanLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel2)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        Item_TaiKhoanLayout.setVerticalGroup(
            Item_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Item_TaiKhoanLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        Item_TrangBanHang.setBackground(new java.awt.Color(138, 91, 43));
        Item_TrangBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_TrangBanHangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Item_TrangBanHangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Item_TrangBanHangMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-setting-30.png"))); // NOI18N
        jLabel5.setText("Trang bán hàng");

        javax.swing.GroupLayout Item_TrangBanHangLayout = new javax.swing.GroupLayout(Item_TrangBanHang);
        Item_TrangBanHang.setLayout(Item_TrangBanHangLayout);
        Item_TrangBanHangLayout.setHorizontalGroup(
            Item_TrangBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_TrangBanHangLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );
        Item_TrangBanHangLayout.setVerticalGroup(
            Item_TrangBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_TrangBanHangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Item_LichSu.setBackground(new java.awt.Color(138, 91, 43));
        Item_LichSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_LichSuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Item_LichSuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Item_LichSuMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-clock-30.png"))); // NOI18N
        jLabel3.setText("Lịch sử xuất kho");

        javax.swing.GroupLayout Item_LichSuLayout = new javax.swing.GroupLayout(Item_LichSu);
        Item_LichSu.setLayout(Item_LichSuLayout);
        Item_LichSuLayout.setHorizontalGroup(
            Item_LichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_LichSuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                .addContainerGap())
        );
        Item_LichSuLayout.setVerticalGroup(
            Item_LichSuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_LichSuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Item_DangXuat.setBackground(new java.awt.Color(138, 91, 43));
        Item_DangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_DangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Item_DangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Item_DangXuatMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-logout-30.png"))); // NOI18N
        jLabel4.setText("Đăng xuất");

        javax.swing.GroupLayout Item_DangXuatLayout = new javax.swing.GroupLayout(Item_DangXuat);
        Item_DangXuat.setLayout(Item_DangXuatLayout);
        Item_DangXuatLayout.setHorizontalGroup(
            Item_DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_DangXuatLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        Item_DangXuatLayout.setVerticalGroup(
            Item_DangXuatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item_DangXuatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_TrangBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_LichSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Item_DangXuat, Item_LichSu, Item_TaiKhoan, Item_TrangBanHang});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Item_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_TrangBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_LichSu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_DangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Item_DangXuat, Item_LichSu, Item_TaiKhoan, Item_TrangBanHang});

        javax.swing.GroupLayout P_MenuItemLayout = new javax.swing.GroupLayout(P_MenuItem);
        P_MenuItem.setLayout(P_MenuItemLayout);
        P_MenuItemLayout.setHorizontalGroup(
            P_MenuItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MenuItemLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        P_MenuItemLayout.setVerticalGroup(
            P_MenuItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_MenuItemLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P_MenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(P_MenuItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuMouseClicked
        // TODO add your handling code here:
        if (!P_MenuItem.isVisible()) {
            P_MenuItem.setVisible(true);
        } else {
            P_MenuItem.setVisible(false);
        }

    }//GEN-LAST:event_MenuMouseClicked

    private void Item_LichSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_LichSuMouseClicked
        // TODO add your handling code here:
//        Item_DangXuat.setBackground(oldColor);
//        Item_TaiKhoan.setBackground(oldColor);
//        Item_QuanLy.setBackground(oldColor);
//
//        Item_LichSu.setBackground(Color.red);

    }//GEN-LAST:event_Item_LichSuMouseClicked

    private void Item_TaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TaiKhoanMouseClicked

    }//GEN-LAST:event_Item_TaiKhoanMouseClicked

    private void Item_TrangBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TrangBanHangMouseClicked
        Fr_BanHang f = new Fr_BanHang();
        if (JOptionPane.showConfirmDialog(null, "Xác nhận chuyển sang giao diện bán hàng?", JOptionPane.ICON_PROPERTY, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JFrame jf;
            Component c = getParent();
            while (!(c instanceof JFrame)) {
                c = c.getParent();
            }
            jf = (JFrame) c;
            jf.setVisible(false);
            f.setVisible(true);
        }

    }//GEN-LAST:event_Item_TrangBanHangMouseClicked

    private void P_MenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_P_MenuItemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_P_MenuItemMouseClicked

    private void Item_DangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_DangXuatMouseClicked
        // TODO add your handling code here:
        Fr_Login f = new Fr_Login();
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn đăng xuất ?", JOptionPane.ICON_PROPERTY, JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            JFrame jf;
            Component c = getParent();
            while (!(c instanceof JFrame)) {
                c = c.getParent();
            }
            jf = (JFrame) c;
            jf.setVisible(false);
            f.setVisible(true);
        }

    }//GEN-LAST:event_Item_DangXuatMouseClicked

    private void Item_TaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TaiKhoanMouseExited
        // TODO add your handling code here:
        Item_TaiKhoan.setBackground(new Color(138, 91, 43));

    }//GEN-LAST:event_Item_TaiKhoanMouseExited

    private void Item_DangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_DangXuatMouseEntered
        Item_DangXuat.setBackground(new Color(222, 184, 135));
    }//GEN-LAST:event_Item_DangXuatMouseEntered

    private void Item_DangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_DangXuatMouseExited
        Item_DangXuat.setBackground(new Color(138, 91, 43));
    }//GEN-LAST:event_Item_DangXuatMouseExited

    private void Item_LichSuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_LichSuMouseEntered
        // TODO add your handling code here:
        Item_LichSu.setBackground(new Color(222, 184, 135));
    }//GEN-LAST:event_Item_LichSuMouseEntered

    private void Item_TaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TaiKhoanMouseEntered
        // TODO add your handling code here:
        Item_TaiKhoan.setBackground(new Color(222, 184, 135));
    }//GEN-LAST:event_Item_TaiKhoanMouseEntered

    private void Item_TrangBanHangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TrangBanHangMouseEntered
        // TODO add your handling code here:
        Item_TrangBanHang.setBackground(new Color(222, 184, 135));
    }//GEN-LAST:event_Item_TrangBanHangMouseEntered

    private void Item_LichSuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_LichSuMouseExited
        // TODO add your handling code here:
        Item_LichSu.setBackground(new Color(138, 91, 43));
    }//GEN-LAST:event_Item_LichSuMouseExited

    private void Item_TrangBanHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TrangBanHangMouseExited
        // TODO add your handling code here:
        Item_TrangBanHang.setBackground(new Color(138, 91, 43));
    }//GEN-LAST:event_Item_TrangBanHangMouseExited
    public static void main(String[] args) {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Item_DangXuat;
    private javax.swing.JPanel Item_LichSu;
    private javax.swing.JPanel Item_TaiKhoan;
    private javax.swing.JPanel Item_TrangBanHang;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel P_MenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
