/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Assets.Custom_Item;

import DAO.ChiTietHoaDon_DAO;
import DAO.HoaDon_DAO;
import GUI.SalesGroup.JF_GoiMonVaThanhToan;
import GUI.SalesGroup.JP_ThongTinBan;
import POJO.Ban;
import POJO.ChiTietHoaDon;
import POJO.SanPham;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author Admin
 */
public class OrderItem extends javax.swing.JPanel {

    private final SanPham sanPham;

    private void thayDoiSoLuong() {
        // Do something when the value of the spinner changes
        int soLuong = (int) nr_SoLuong.getValue();
        int tongTien = soLuong * Integer.parseInt(txt_Gia.getText());
        txt_TongTien.setText(String.valueOf(tongTien));
        ChiTietHoaDon cthd = new ChiTietHoaDon(JF_GoiMonVaThanhToan.hd.getMaHoaDon(),sanPham.getMaSanPham(), soLuong, tongTien);
        int[] check = {0, 0};
        JF_GoiMonVaThanhToan.listCTHD.forEach(sp -> {
            if (sp.getMaSanPham() == cthd.getMaSanPham()) {
                check[0] = 1;
                return;
            }
            check[1]++;
        });
        if (check[0] != 1) {
            JF_GoiMonVaThanhToan.listCTHD.add(cthd);
        } else {
            if (soLuong > 0) {
                JF_GoiMonVaThanhToan.listCTHD.get(check[1]).setSoLuong(soLuong);
                JF_GoiMonVaThanhToan.listCTHD.get(check[1]).setTongTien(tongTien);
            } else {
                JF_GoiMonVaThanhToan.listCTHD.remove(check[1]);
            }
        }
        JF_GoiMonVaThanhToan.panel_ThongTinBan1.load_DanhSachDatMon(JF_GoiMonVaThanhToan.listCTHD);
        System.out.println(JF_GoiMonVaThanhToan.listCTHD.toString());
    }

    private void load_nr_SoLuong() {
        nr_SoLuong.addChangeListener((ChangeEvent e) -> {
            thayDoiSoLuong();
        });
        nr_SoLuong.removeChangeListener((ChangeEvent e) -> {
            thayDoiSoLuong();
        });
    }

    /**
     * Creates new form OrderItem
     *
     * @param sanPham
     * @param soLuong
     */
    public OrderItem(SanPham sanPham, int soLuong) {
        initComponents();
        load_nr_SoLuong();

        this.sanPham = sanPham;
        txt_TenSanPham.setText(sanPham.getTenSanPham());
        txt_Gia.setText(String.valueOf(sanPham.getGiaBan()));
        nr_SoLuong.setValue(soLuong);
        anhSanPham.setImage(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/SanPham/" + sanPham.getHinhAnh())));
        txt_TongTien.setText(String.valueOf(soLuong*sanPham.getGiaBan()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new Assets.Custom_Item.PanelRound();
        anhSanPham = new Assets.Custom_Item.ImagePanel();
        txt_TenSanPham = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nr_SoLuong = new javax.swing.JSpinner();
        txt_TongTien = new javax.swing.JLabel();
        txt_Gia = new javax.swing.JLabel();

        setOpaque(false);

        panelRound1.setBackground(new java.awt.Color(222, 184, 135));
        panelRound1.setRoundBottomLeft(30);
        panelRound1.setRoundBottomRight(30);
        panelRound1.setRoundTopLeft(30);
        panelRound1.setRoundTopRight(30);

        anhSanPham.setBackground(new java.awt.Color(222, 184, 135));
        anhSanPham.setImage(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/SanPham/Bacxiu.png"))); // NOI18N

        javax.swing.GroupLayout anhSanPhamLayout = new javax.swing.GroupLayout(anhSanPham);
        anhSanPham.setLayout(anhSanPhamLayout);
        anhSanPhamLayout.setHorizontalGroup(
            anhSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 105, Short.MAX_VALUE)
        );
        anhSanPhamLayout.setVerticalGroup(
            anhSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        txt_TenSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TenSanPham.setText("Tên sản phẩm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Giá :");

        nr_SoLuong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nr_SoLuong.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nr_SoLuongStateChanged(evt);
            }
        });

        txt_TongTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_TongTien.setText("jLabel2");

        txt_Gia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Gia.setText("jLabel2");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Gia))
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(nr_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_TongTien))
                    .addComponent(txt_TenSanPham))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(txt_TenSanPham)
                        .addGap(18, 18, 18)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_Gia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nr_SoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_TongTien)))
                    .addComponent(anhSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nr_SoLuongStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nr_SoLuongStateChanged
        if ((int) nr_SoLuong.getValue() < 0) {
            nr_SoLuong.setValue(0);
        }
    }//GEN-LAST:event_nr_SoLuongStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Assets.Custom_Item.ImagePanel anhSanPham;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner nr_SoLuong;
    private Assets.Custom_Item.PanelRound panelRound1;
    private javax.swing.JLabel txt_Gia;
    private javax.swing.JLabel txt_TenSanPham;
    private javax.swing.JLabel txt_TongTien;
    // End of variables declaration//GEN-END:variables
}
