/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Assets.Custom_Item;

import GUI.SalesGroup.JP_ThongTinBan;
import POJO.Ban;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class TableItem extends javax.swing.JPanel {

    Ban ban;
    /**
     * Creates new form TableItem
     *
     * @param ban
     */
    public TableItem(Ban ban) {
        this.ban = ban;
        initComponents();
        
        lb_SoBan.setText(String.valueOf(ban.getSoBan()));
        lb_SoCho.setText(String.valueOf(ban.getSoGhe()) + " chỗ");
        lb_KhuVuc.setText(ban.getKhuVuc());

        if (ban.getTrangThai()) {
            lb_TrangThai.setText("Đang sử dụng");
            panel_BanItem.setBackground(new Color(153,255,153));
        } else {
            menu_QLBan1.setVisible(false);
            lb_TrangThai.setText("Trống");
            panel_BanItem.setBackground(new Color(235,213,186));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_QLBan1 = new Assets.Custom_Item.Menu_QLBan(ban);
        panel_BanItem = new Assets.Custom_Item.PanelRound();
        lb_SoCho = new javax.swing.JLabel();
        lb_KhuVuc = new javax.swing.JLabel();
        lb_TrangThai = new javax.swing.JLabel();
        panelRound2 = new Assets.Custom_Item.PanelRound();
        lb_SoBan = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(menu_QLBan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panel_BanItem.setBackground(new java.awt.Color(235, 213, 186));
        panel_BanItem.setRoundBottomLeft(50);
        panel_BanItem.setRoundBottomRight(50);
        panel_BanItem.setRoundTopLeft(50);
        panel_BanItem.setRoundTopRight(50);
        panel_BanItem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_SoCho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-bench-30.png"))); // NOI18N
        lb_SoCho.setText("4 chỗ");
        panel_BanItem.add(lb_SoCho, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, -1));

        lb_KhuVuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-near-me-30.png"))); // NOI18N
        lb_KhuVuc.setText("Sảnh A");
        panel_BanItem.add(lb_KhuVuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 13, 100, -1));

        lb_TrangThai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_TrangThai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_TrangThai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/img/icons8-ok-30.png"))); // NOI18N
        lb_TrangThai.setText("Trống");
        panel_BanItem.add(lb_TrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 160, 38));

        panelRound2.setBackground(new java.awt.Color(223, 164, 88));
        panelRound2.setRoundBottomRight(50);
        panelRound2.setRoundTopLeft(50);

        lb_SoBan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_SoBan.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lb_SoBan.setText("32 ");
        lb_SoBan.setToolTipText("");
        panelRound2.add(lb_SoBan);

        panel_BanItem.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 40, 40));

        add(panel_BanItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 160));
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lb_KhuVuc;
    private javax.swing.JLabel lb_SoBan;
    private javax.swing.JLabel lb_SoCho;
    private javax.swing.JLabel lb_TrangThai;
    private Assets.Custom_Item.Menu_QLBan menu_QLBan1;
    private Assets.Custom_Item.PanelRound panelRound2;
    private Assets.Custom_Item.PanelRound panel_BanItem;
    // End of variables declaration//GEN-END:variables
}
